version: "3.9"
services:

  # FastAPI Application
  backend:
    build: .
    container_name: tahrirgoh-backend
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy

  # PostgreSQL Database
  db:
    image: postgres
    container_name: tahrirgoh-db
    volumes:
      - tahrirgoh-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tahrirgoh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "tahrirgoh"]
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
  tahrirgoh-data:
